const PictureActionTypes = {
	PICTURE_ADD_SUCCESS: "PICTURE_ADD_SUCCESS",
	PICTURE_ADD_FAILURE: "PICTURE_ADD_FAILURE",
	TOGGLE_ADD_PICTURE: "TOGGLE_ADD_PICTURE",
	PICTURE_FETCH_SUCCESS: "PICTURE_FETCH_SUCCESS",
	PICTURE_FETCH_FAILURE: "PICTURE_FETCH_FAILURE",
};

export default PictureActionTypes;
